[package]
name = "create-gh-repo"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
hyper = "0.9"
tempfile = "2.1"
git2 = "0.4"
url = "1.2"
